### PR TITLE
Feature/9 lauch script

### LINKED ISSUE #9: Launch script
## Description
A script that launches backend and frontend

## Acceptance criteria
- [ ] Script that launches backend and frontend

### PR DESCRIPTION
**Pull request by CR1337**
Fixes #9 

There now exists a convenient launch script at `bin/run`. It passes all command line arguments to the backend. The backend then asynchronously launches the frontend and also takes care if its termination.

There also were added multiple thousand files after executing npm start. I guess that is normal?

### CODE REVIEW

**Comment by LucasDerReisende** [comment]
Please make sure to exclude the node_modules directory, since it should not be commited, is it not in the .gitignore

**Comment by LucasDerReisende** [comment]
Just updated .gitignore on dev, so should not be included anymore

**Comment by CR1337** [comment]
> Please make sure to exclude the node_modules directory, since it should not be commited, is it not in the .gitignore

I reverted the last commit and then force pushed to remote. `node_modules` is included in `.gitignore`. Nevertheless its content is part of the changed files. If you don't have another idea to solve this I will delete this branch and start over clean.

**Comment by CR1337** [comment]
Ok, I solved it. In `.gitignore` it has to be `frontend/node_packages` instead of just `node_packages`. Maybe you check if you have to adjust more frontend stuff in `.gitignore` ;)

Do you approve now?

**Pull request closed without merging**
